<?php
/*
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

//unsolved -> timesout before finishing
*/



function getTriangularNumber($number) {
/*
	for ($i=0; $i <= $number; $i++) { 
		$out += $i;
	}

	return $out;
*/
	return (($number*($number+1))/2);
}

function getFactors($number) {
//list each factor (28 = 28,14,7,4,2,1)	
	$factors = array();

	for ($i=1; ($i*2) <= $number; $i++) { 
		if ($number % $i == 0) {
			$factors[] = $i;
		}
	}
	return $factors;
}

$currentBase = 1;
$currentTriangle = 0;
$currentFactors = array();

do {
	$currentBase++;
	$currentTriangle = getTriangularNumber($currentBase);
	$currentFactors = getFactors($currentTriangle);
} while (count($currentFactors) <= 500);



echo "CurrentBase: $currentBase<br />";
echo "CurrentTriangle: $currentTriangle<br />";
echo 'CurrentCount: '.count($currentFactors).'<br />';
foreach ($currentFactors as $value) {
	echo "CurrentFactors: $value<br />";
}
echo '<br />';

?>